/**
 * 
 */
package no.uib.info216.facebook;

import facebook4j.Facebook;
import facebook4j.FacebookException;
import facebook4j.FacebookFactory;
import facebook4j.auth.AccessToken;
import no.uib.info216.RDF.RDFHandler;
import org.apache.jena.ontology.OntModel;
import org.apache.jena.ontology.OntModelSpec;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;


/**
 * @author Marius This is the class which runs the program.
 */
public class RandomUserGeneration {


/*	*//**
	 * This is the main method which runs the program.
	 * 
	 * @param args
	 * @throws FacebookException
	 *//*
	public static void main(String[] args) throws FacebookException {
		RDFHandler rdfHandler = new RDFHandler();
		FacebookData data = new FacebookData();
		cm.getIr().getInterests(data.getUser());

		ArrayList<FacebookUser> users = createUserWithRandomInterests(10); //Creates 4 "Fake" users.
		test(users);
		cm.createUsersModel(users);
		rdfHandler.addModel(cm.getUsersModel());


		rdfHandler.addModel(parse());
		writeToFile(data.getUser());

	}*/



	/**
	 * This method selects randomly chosen Strings from an arrayList
	 * and adds these to another list. Only 1/4 or 1/2 of Strings from the
	 * Already existing list are added to the new randomList which is returned.
	 * @param arrayList to choose random values from.
	 * @return arrayList with random values from param.
     */
	public ArrayList<String> selectRandomInterestsFromList (ArrayList<String> arrayList){
		Random random = new Random();

		Set<String> randomUniqueList = new HashSet<String>();
		ArrayList<String> randomList = new ArrayList<String>();

		int size = 0;
		if(arrayList.size() < 10){
			size = arrayList.size()/2;
		} else{
			size = arrayList.size()/4;
		}

		for(int i = 0;i < size; i++){
			int  n = random.nextInt(arrayList.size()) + 0;
			String s = arrayList.get(n);
				randomUniqueList.add(s);
		}
		randomList.addAll(randomUniqueList);
		return randomList;
	}

	/**
	 * This method creates a new list of Facebook users with lists of interests
	 * that is randomly generated by picking random interests from an already
	 * existing list. A new ArrayList is returned containing the new FaceBookUser's.
	 * @param numberOfUsers to be generated.
	 * @return ArrayList - A list of FacebookUser objects.
	 */
	public ArrayList<FacebookUser> createUserWithRandomInterests(int numberOfUsers, Interests ir){
		ArrayList<String> names = new ArrayList<String>();
		names.add("Guri"); names.add("Pål"); names.add("Ole"); names.add("Eirik"); names.add("Knut");
		Random random = new Random();

		ArrayList<FacebookUser> randomUsers = new ArrayList<FacebookUser>();
		for(int i = 0; i < numberOfUsers; i++) {
			ArrayList<String> tvShows = selectRandomInterestsFromList(ir.getTvShows());
			ArrayList<String> movies = selectRandomInterestsFromList(ir.getMovies());
			ArrayList<String> music = selectRandomInterestsFromList(ir.getMusic());
			ArrayList<String> book = selectRandomInterestsFromList(ir.getBook());
			ArrayList<String> games = selectRandomInterestsFromList(ir.getGames());
			ArrayList<String> events = selectRandomInterestsFromList(ir.getEvents());
			ArrayList<String> likes = selectRandomInterestsFromList(ir.getLikes());

			FacebookUser fu = new FacebookUser(tvShows, movies, music, book, games, events, likes);
			int r = random.nextInt(names.size()) + 0;
			int randomId = random.nextInt(1000) + 1;
			fu.setName(names.get(r));
			fu.setId(randomId);
			randomUsers.add(fu);
		}

		return randomUsers;
	}

	/**
	 * This method was created for testing purposes only and does not
	 * really do much other than check if lists are empty or not.
	 * An example of how it can be used could be.
	 * test(createUserWithRandomInterests(5); Also shown in the main method.
	 * @param a - An arrayList of FacebookUser objects.
     */
	public void test(ArrayList<FacebookUser> a){

		for (int i = 0; i < a.size(); i++){
			for (String s : a.get(i).getEvents()){
				System.out.println(s);
			}
			System.out.println("NUMBER: " + (i+1) + "  ###############################################");
		}
	}

	/**
	 * This method selects a random user from a list
	 * containing FacebookUser objects.
	 * @param users
	 * @return
     */
	public FacebookUser selectRandomUser(ArrayList<FacebookUser> users){
		Random random = new Random();
		int user = random.nextInt(users.size()) + 0;

		FacebookUser fu = users.get(user);
		return fu;
	}

}
